version: "3"
services:
  nginx:
    container_name: ornikar_nginx
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    container_name: ornikar_php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    image: ornikar/php:7.3-fpm-alpine3.10
    restart: always
    expose:
      - "9000"
    volumes:
      - ./src:/var/www/html
