version: '2'

vars:
  IMAGE: training/first
  VERSION: 1.0.0
  TARGET_PORT: 3000
  HOST_PORT: 8080

tasks:
  build:
    silent: true
    desc: Build my Docker image
    cmds:
      - cmd: docker build -t {{ .IMAGE }}:latest .
      - cmd: "echo 'Time to run: task run'"

  tag:
    silent: true
    desc: Tag my Docker image
    cmds:
      - cmd: docker tag {{ .IMAGE }}:latest {{ .IMAGE }}:{{ .VERSION }}

  run:
    silent: true
    desc: Run a container from my image
    cmds:
      - cmd: docker run --rm --name first -p {{ .HOST_PORT }}:{{ .TARGET_PORT }} {{ .IMAGE }}:latest